name: Build Docker images
 
on:
  push:
    branches: ["main"]
    paths-ignore: 
      - "/Dockerfile"
      - "/.dockerignore"
      - "/.env*"
      - "/README.md"
      - "/.github/**"
      - "/.vscode/**"

 
jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
 
    steps:
      - name: Send Discord Notification
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "üöÄ Deployment started for ${{ github.repository }}..."

      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Make sure to replace with your own namespace and repository
          tags: |
            abotica/my-portfolio:latest 
          platforms: linux/amd64

      - name: Send Discord Notification
        uses: tsickert/discord-webhook@v7.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "‚úÖ Deployment succeeded for ${{ github.repository }}!"
          
      - name: Send Discord Notification
        uses: tsickert/discord-webhook@v7.0.0
        if: failure()
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "‚ùå Deployment failed for ${{ github.repository }}. Status code: ${{ job.status }}."